# Generated by Django 5.2 on 2026-01-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_mountmeruslide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mountmeruslide',
            options={'ordering': ['title'], 'verbose_name': 'Mount Meru Slide', 'verbose_name_plural': 'Mount Meru Slides'},
        ),
        migrations.AddField(
            model_name='trip_itinerary_db',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip_itinerary_db',
            name='elevation_end',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip_itinerary_db',
            name='elevation_start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip_itinerary_db',
            name='habitat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip_itinerary_db',
            name='hiking_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
